### ISSUE TITLE
crash with bigger stacks when trying to insert a stack larger than the bundle's maximum size

### ISSUE THREAD

**Issue by NyanMC** [Cheaterpaul/BetterBundles#3]
bigger stacks link: https://www.curseforge.com/minecraft/mc-mods/bigger-stacks

steps to reproduce:
1. install both mods
2. acquire a stack with over 512 items
3. attempt to insert this stack into a netherite bundle
4. game crashes

crash report: https://pastebin.com/k3kG08V0 (changed to a pastebin as of 1/29/22 due to the old link being seemingly invalid)

**Comment by NyanMC** [comment]
update: apparently it happens just from inserting any item regardless of stack size as long as both mods are installed (perhaps due to how high i have my stack sizes set to? idk)

**Comment by Cheaterpaul** [comment]
This is an issue with the way bundles calculates their used slots when inserting stacks.
Because the max slot site is increased to much they would occupy 0 slots of the bundle causing this error.

So this is an issue with Bigger Stacks and bundles in general. 

But i added a fail safe so it does not crash anymore, but sends a chat message
